from __future__ import annotations
import asyncio
import json
from typing import TYPE_CHECKING
from gabagent.api.models import ChatMessage, ToolCallSpec, ToolResult
from gabagent.tui.renderer import console
from gabagent.tui.streaming import StreamingDisplay
from gabagent.tui.tool_display import ToolCallDisplay

if TYPE_CHECKING:
    from gabagent.agent.context import AgentContext
    from gabagent.agent.router import ModelRouter

CONTEXT_WARN_RATIO = 0.7
CONTEXT_COMPACT_RATIO = 0.85

# Minimal system prompt for the local model — intentionally short to save tokens.
# The session briefing (generated by arya on /local on) is appended separately.
_LOCAL_SYSTEM = (
    "You are a local AI assistant running via Ollama on the user's machine — not Gab or Arya. "
    "You have access to shell commands, file reading/writing/editing, web search, and code analysis tools. "
    "Use tools when the task genuinely requires it — not for greetings or simple conversational responses. "
    "Be direct and concise."
)
_LOCAL_CONTEXT_WINDOW = 10  # number of recent non-system messages sent to local model


def _active_client(ctx: AgentContext):
    """Return local client when local mode is on, otherwise primary."""
    if ctx.local_mode and ctx.local_client is not None:
        return ctx.local_client
    return ctx.client

_TOOL_KEEP_RECENT = 6    # keep last N tool results in full
_TOOL_TRIM_CHARS = 400   # trim older ones to this many chars


def _trim_old_tool_results(messages: list[ChatMessage]) -> list[ChatMessage]:
    """Trim old tool result messages to prevent O(n²) context growth.

    The last _TOOL_KEEP_RECENT results are kept in full. Older ones are
    truncated to _TOOL_TRIM_CHARS — the model already processed them when
    they were returned; they don't need to be re-read verbatim on every turn.
    """
    tool_positions = [i for i, m in enumerate(messages) if m.role == "tool"]
    cutoff = len(tool_positions) - _TOOL_KEEP_RECENT
    if cutoff <= 0:
        return messages
    trim_indices = set(tool_positions[:cutoff])
    out: list[ChatMessage] = []
    for i, m in enumerate(messages):
        if i in trim_indices and m.content and len(m.content) > _TOOL_TRIM_CHARS:
            clipped = m.content[:_TOOL_TRIM_CHARS]
            note = f"\n…[{len(m.content) - _TOOL_TRIM_CHARS} chars not repeated in history]"
            out.append(ChatMessage(role="tool", content=clipped + note, tool_call_id=m.tool_call_id))
        else:
            out.append(m)
    return out


def _estimate_tokens(messages: list[ChatMessage]) -> int:
    total = sum(
        len(json.dumps(m.to_dict())) for m in messages
    )
    return int(total / 3.5)


async def _compact_context(ctx: AgentContext) -> None:
    messages = ctx.session.messages()
    user_assistant = [m for m in messages if m.role in ("user", "assistant")]
    if len(user_assistant) < 4:
        console.print("[dim]Nothing to compact — conversation is too short.[/dim]", markup=True)
        return
    tokens_before = _estimate_tokens(
        [ChatMessage(role="system", content=ctx.system_prompt)]
        + [m for m in messages if m.role != "system"]
    )
    console.print(
        f"[dim]Compacting context ({tokens_before:,} tokens)…[/dim]", markup=True
    )
    summary_messages = [
        ChatMessage(role="system", content=ctx.system_prompt),
        *user_assistant,
        ChatMessage(
            role="user",
            content=(
                "Please summarize the conversation above into a concise context summary "
                "that preserves all important decisions, code changes, and findings. "
                "Start with '# Conversation Summary\\n\\n'."
            ),
        ),
    ]
    summary = await ctx.client.complete_simple(summary_messages)
    new_messages = [
        ChatMessage(role="system", content=f"{ctx.system_prompt}\n\n{summary}"),
    ]
    import time
    from pathlib import Path
    old_path = ctx.session.path
    pre_path = old_path.with_name(
        f"{old_path.stem}.pre-compact-{int(time.time())}.jsonl"
    )
    import shutil
    shutil.copy2(old_path, pre_path)
    ctx.session.replace_all(new_messages)
    ctx.token_estimate = _estimate_tokens(new_messages)
    console.print(
        f"[gab.accent]◆[/gab.accent] [dim]Context compacted: "
        f"{tokens_before:,} → {ctx.token_estimate:,} tokens "
        f"({int((1 - ctx.token_estimate / tokens_before) * 100)}% reduction).[/dim]",
        markup=True,
    )


async def run_loop(ctx: AgentContext, initial_prompt: str | None = None) -> None:
    from gabagent.tools.registry import registry

    from gabagent.tui.thinking import ThinkingIndicator
    thinking = ThinkingIndicator(console.file)
    ctx._thinking_indicator = thinking  # Store for tool execution state changes
    streaming = StreamingDisplay(console, thinking=thinking)
    tool_display = ToolCallDisplay(console)
    hooks_runner = None
    try:
        from gabagent.hooks.runner import HookRunner
        hooks_runner = HookRunner(ctx.config)
    except Exception:
        pass

    perm_engine = None
    try:
        from gabagent.permissions.engine import PermissionEngine
        perm_engine = PermissionEngine(ctx.config)
    except Exception:
        pass

    router: ModelRouter | None = None
    if not ctx.force_model and ctx.config.router.enabled:
        try:
            from gabagent.agent.router import ModelRouter
            router = ModelRouter(ctx.config)
        except Exception:
            pass

    if hooks_runner:
        await hooks_runner.run_session_start()

    # Check bridge inbox for messages from Claude Code
    try:
        from gabagent.bridge import read_inbox
        from rich.panel import Panel
        pending = read_inbox(mark_read=True)
        if pending:
            if not ctx.headless:
                for msg in pending:
                    topic = msg.get("topic", "note")
                    console.print(Panel(
                        msg["message"],
                        title=f"[bold cyan]✉ Claude Code [{topic}][/bold cyan]",
                        border_style="cyan",
                        padding=(0, 1),
                        width=min(80, console.width - 2),
                    ))
            # Inject into conversation history so the model can reference them
            combined = "\n\n".join(
                f"[Claude Code — {m.get('topic','note')}]: {m['message']}"
                for m in pending
            )
            ctx.session.append_message(ChatMessage(
                role="system",
                content=f"Messages received from Claude Code at session start:\n\n{combined}",
            ))
    except Exception:
        pass

    if initial_prompt:
        ctx.session.append_message(ChatMessage(role="user", content=initial_prompt))

    _force_input = False

    while True:
        _msgs = ctx.session.messages()
        _last_role = _msgs[-1].role if _msgs else None
        if _force_input or (not initial_prompt and _last_role not in ("user", "tool")):
            _force_input = False
            ctx.active_model = None  # reset only when starting a new user turn
            if not ctx.headless:
                from gabagent.tui.input_handler import InputHandler
                handler = InputHandler(vim_mode=ctx.config.vim_mode)
                if ctx.local_mode and ctx.config.local_model:
                    badge = f"LOCAL:{ctx.config.local_model}"
                elif ctx.force_model:
                    badge = ctx.rate_limiter.forced_badge(ctx.config.model)
                else:
                    badge = ctx.rate_limiter.badge
                user_input = await handler.prompt(badge)
                if user_input is None:
                    break

                stripped = user_input.strip()
                if stripped.startswith("/"):
                    try:
                        from gabagent.slash.commands import handle_slash
                        if await handle_slash(stripped, ctx):
                            continue
                    except ImportError:
                        pass

                if not stripped:
                    continue

                if hooks_runner:
                    extra = await hooks_runner.run_user_prompt_submit(stripped)
                    if extra:
                        stripped = f"{stripped}\n\n[Hook context]\n{extra}"

                ctx.session.append_message(ChatMessage(role="user", content=stripped))
            else:
                break

        initial_prompt = None

        messages = ctx.session.messages()

        if ctx.local_mode:
            # Send only: minimal local system prompt + arya briefing + last N messages.
            # This keeps the local model's input small so time-to-first-token stays fast.
            local_sys = _LOCAL_SYSTEM + f"\n\nWorking directory: {ctx.cwd}"
            if ctx.local_context_summary:
                local_sys += f"\n\n{ctx.local_context_summary}"
            recent = [m for m in messages if m.role != "system"][-_LOCAL_CONTEXT_WINDOW:]
            all_messages = [ChatMessage(role="system", content=local_sys)] + recent
            ctx.token_estimate = _estimate_tokens(all_messages)
        else:
            # Merge any system messages stored in the session into the system prompt.
            # Some APIs (including Gab AI) reject consecutive system messages or
            # system messages in non-leading positions.
            extra_sys = [m.content for m in messages if m.role == "system" and m.content]
            non_sys_messages = _trim_old_tool_results([m for m in messages if m.role != "system"])
            system_content = ctx.system_prompt
            if extra_sys:
                system_content = ctx.system_prompt + "\n\n" + "\n\n".join(extra_sys)
            system_msg = ChatMessage(role="system", content=system_content)
            all_messages = [system_msg] + non_sys_messages

            ctx.token_estimate = _estimate_tokens(all_messages)
            if ctx.token_estimate > ctx.config.max_context_tokens * CONTEXT_COMPACT_RATIO:
                await _compact_context(ctx)
                messages = ctx.session.messages()
                extra_sys = [m.content for m in messages if m.role == "system" and m.content]
                non_sys_messages = _trim_old_tool_results([m for m in messages if m.role != "system"])
                system_content = ctx.system_prompt
                if extra_sys:
                    system_content = ctx.system_prompt + "\n\n" + "\n\n".join(extra_sys)
                system_msg = ChatMessage(role="system", content=system_content)
                all_messages = [system_msg] + non_sys_messages
            elif ctx.token_estimate > ctx.config.max_context_tokens * CONTEXT_WARN_RATIO:
                console.print(
                    f"[warning]Context {ctx.token_estimate:,} tokens "
                    f"({int(ctx.token_estimate / ctx.config.max_context_tokens * 100)}% full). "
                    "Use /compact to compress.[/warning]",
                    markup=True,
                )

        if not ctx.headless:
            thinking.set_state("THINKING")
            thinking.start()

        # Intent-based routing — only on fresh user turns, not tool continuations.
        # Skip entirely in local mode; routing arya↔sonnet doesn't apply there.
        if router and _last_role == "user" and ctx.active_model is None and not ctx.local_mode:
            last_user = next(
                (m.content for m in reversed(messages) if m.role == "user" and m.content),
                "",
            )
            ctx.active_model = await router.classify_intent(last_user, ctx.client)

        tools = registry.get_schemas()

        text_buf = ""
        tool_calls: list[ToolCallSpec] = []

        try:
            display_model = ctx.config.local_model if ctx.local_mode else (ctx.active_model or ctx.config.model)
            request_model = None if ctx.local_mode else ctx.active_model
            streaming.start(model=display_model)
            async for chunk in _active_client(ctx).stream_complete(
                all_messages, tools or None, model=request_model
            ):
                if isinstance(chunk, str):
                    streaming.append(chunk)
                    text_buf += chunk
                elif isinstance(chunk, list):
                    tool_calls = chunk
            streaming.stop()
            # Local models sometimes emit malformed tool calls with no name; discard them.
            tool_calls = [tc for tc in tool_calls if tc.name]
            # Local models that reject tool schemas (e.g. deepseek-r1 via Ollama) output
            # tool calls as JSON text. Parse them from the accumulated buffer.
            if ctx.local_mode and not tool_calls and text_buf:
                from gabagent.api.client import _extract_text_tool_calls
                prose, parsed = _extract_text_tool_calls(text_buf)
                if parsed:
                    tool_calls = parsed
                    text_buf = prose
        except Exception as e:
            streaming.stop()
            if not ctx.headless:
                from gabagent.tui.diagnostic import render_diagnostic
                thinking.set_state("ERROR")
                render_diagnostic(
                    console,
                    title="API Error",
                    context="Streaming completion request",
                    cause=str(e),
                    recovery="Forcing fresh user input",
                )
                thinking.stop()
            if ctx.headless:
                break
            _force_input = True
            continue

        if text_buf:
            ctx.session.append_message(
                ChatMessage(role="assistant", content=text_buf, tool_calls=tool_calls or None)
            )

        if not tool_calls:
            if hooks_runner:
                await hooks_runner.run_stop(text_buf)
            if ctx.headless:
                break
            continue

        if not text_buf:
            ctx.session.append_message(
                ChatMessage(role="assistant", content=None, tool_calls=tool_calls)
            )

        results = await _execute_tool_calls(
            tool_calls, ctx, perm_engine, hooks_runner, tool_display, router
        )

        for tc, result in zip(tool_calls, results):
            ctx.session.append_message(
                ChatMessage(
                    role="tool",
                    content=result.to_content(),
                    tool_call_id=tc.id,
                )
            )


async def _execute_tool_calls(
    tool_calls: list[ToolCallSpec],
    ctx: AgentContext,
    perm_engine,
    hooks_runner,
    tool_display: ToolCallDisplay,
    router: ModelRouter | None = None,
) -> list[ToolResult]:
    from gabagent.tools.registry import registry
    from gabagent.api.models import ToolResult

    parallel: list[ToolCallSpec] = []
    serial: list[ToolCallSpec] = []

    for tc in tool_calls:
        tool_cls = registry.get_tool(tc.name)
        if tool_cls and getattr(tool_cls, "allows_parallel", True):
            parallel.append(tc)
        else:
            serial.append(tc)

    results: dict[str, ToolResult] = {}

    async def _run_one(tc: ToolCallSpec) -> ToolResult:
        import time
        try:
            args = json.loads(tc.arguments) if tc.arguments else {}
        except Exception:
            args = {}

        if perm_engine:
            from gabagent.permissions.engine import Decision
            decision = perm_engine.check(tc.name, args)
            if decision == Decision.DENY:
                return ToolResult(output="", error=f"Blocked by permissions: {tc.name}")
            if decision == Decision.PROMPT:
                # Pluggable approval: voice mode supplies ctx.approval_hook
                # (voice_approve); the TUI falls back to interactive_approve.
                approve = getattr(ctx, "approval_hook", None)
                if approve is None:
                    from gabagent.permissions.prompts import interactive_approve
                    approve = interactive_approve
                approved = await approve(tc.name, args, ctx)
                if not approved:
                    return ToolResult(output="", error=f"Denied by user: {tc.name}")

        if hooks_runner:
            blocked, reason = await hooks_runner.run_pre_tool(tc.name, args)
            if blocked:
                return ToolResult(output="", error=f"Blocked by hook: {reason}")

        # Tool-triggered escalation
        if router and not ctx.force_model:
            override = router.check_tool_complexity(tc.name, args)
            if override and override != (ctx.active_model or router.simple_model):
                ctx.active_model = override
                if not getattr(ctx, "voice_mode", False):
                    console.print(
                        f"[gab.accent]▸[/gab.accent] [dim]escalating to {override} (complex tool)[/dim]", markup=True
                    )

        start_time = time.time()
        tool_display.show_start(tc.name, tc.arguments)
        
        # Set state to indicate tool execution
        from gabagent.tui.thinking import ThinkingIndicator
        if hasattr(ctx, '_thinking_indicator'):
            ctx._thinking_indicator.set_state("TOOL_EXECUTING")
        
        result = await registry.dispatch(tc.name, args, ctx)
        duration = time.time() - start_time
        
        # Reset state back to thinking
        if hasattr(ctx, '_thinking_indicator'):
            ctx._thinking_indicator.set_state("THINKING")

        # Reactive escalation
        if router and not ctx.force_model:
            override = router.check_reactive(tc.name, result.exit_code, ctx.active_model)
            if override:
                ctx.active_model = override
                if not getattr(ctx, "voice_mode", False):
                    console.print(
                        f"[gab.accent]▸[/gab.accent] [dim]escalating to {override} (command failed)[/dim]", markup=True
                    )

        if hooks_runner:
            await hooks_runner.run_post_tool(tc.name, args, result)

        tool_display.show_result(
            tc.name,
            result.to_content(),
            is_error=not result.success,
            extra=f" ({duration:.2f}s)",
        )
        return result

    if parallel:
        async with asyncio.TaskGroup() as tg:
            tasks = {tc.id: tg.create_task(_run_one(tc)) for tc in parallel}
        for tc in parallel:
            results[tc.id] = tasks[tc.id].result()

    for tc in serial:
        results[tc.id] = await _run_one(tc)

    return [results[tc.id] for tc in tool_calls]
